name: dotnet package

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [4.7.2]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NETFramework
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
